version: '3'
services:
  jenkins:
    container_name: jenkins-docker
    image: aczulet10/jenkins-docker
    build:
      context: .    
    ports:
      - "8081:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
networks:
  net:
